rm *.tar.gz
rm application.log
rm custom_replay_0.json
rm custom_replay_1.json
rm test.log
rm metrics.csv
rm replay.html
rm dashboard.html
rm mosfet
rm DEBUG
rm valgrind_report_player_0.txt
rm valgrind_report_player_1.txt